apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask.fullname" . }}-app
  labels:
    {{- include "flask.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: "5000"
  selector:
    {{- include "flask.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask.fullname" . }}-redis
  labels:
    {{- include "flask.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceRedis.type }}
  ports:
    - port: {{ .Values.serviceRedis.port }}
      targetPort: 6379
      protocol: TCP
      name: "6379"

  selector:
    {{- include "flask.selectorLabels.svc" . | nindent 6}}